import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";
import Slider from "../components/Slider";

import ReliableSect from "../components/ReliableSect";
import OurBSect from "../components/OurBSect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sinamm Development </title>
        <meta
          name='description'
          content='Generated by Nextjs with Tailwindcss'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Slider />
      <ReliableSect />
      <OurBSect />
    </>
  );
}
